build: false

environment:   
    PYTHON_HOME: "C:\\Python37"
    
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

install:
    - ps: Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
    - ps: Start-Sleep -s 10
    - ps: Restart-Computer -Force
    - ps: Start-Sleep -s 10

build_script:
  - python writeToFile.py